trainer:
  gpus: 1
  min_epochs: 20
  max_epochs: 100
  precision: 16
  benchmark: True
experiment:
  task: "byol_naipcdl_train"
  name: "byol_naipcdl_train"
  run:
    fit: True
    test: False
  module:
    model: "byol"
    encoder: "resnet18"
    encoder_name: ${experiment.module.encoder}
    in_channels: 4
    imagenet_pretrained: True
    image_size:
      - 50
      - 50
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
  datamodule:
    naip_root_dir: "/scratch/NAIP"
    batch_size: 128
    train_length: 100000
    val_length: 15000
    num_workers: 4
    patch_size: 50
    dataset_split: "roi_split_grid"
    number_of_cells: 12
    area_of_interest:
      - -120.25
      - -119.65
      - 36.45
      - 37.05
      - "2016-01-01"
      - "2017-01-01"
      - "EPSG:4326"
      - "EPSG:26911"
    train_sampler_class: "RandomGeoSampler"
    val_sampler_class: "RandomGeoSampler"
    val_pct: 0.14
    test_pct: 0.14
    cache: True
    cache_size: 75
    pin_memory: True
logger:
  name: "wandb"
  offline: False
  project_name: "master-thesis"
