trainer:
  gpus: [1]
  max_epochs: 100
  precision: 32
  benchmark: True
  replace_sampler_ddp: False
  limit_train_batches: 800
  limit_val_batches: 50 
experiment:
  task: "cae_bigearthnet_train"
  name: "cae_bigearthnet_train"
  run:
    fit: True
    test: False
  module:
    model: "cae"
    encoder_name: "vit"
    sensor: "naip"
    imagenet_pretrained: False
    pretrained: False
    image_size: 120
    crop_size: 112
    patch_size: 8
    batch_size: ${experiment.datamodule.batch_size} 
    channel_wise: True
    channel_shuffle: True
    mask_tokens_encoder: False
    mask_tokens_decoder: True
    mask_tokens_reduction_encoder: False
    mask_tokens_reduction_decoder: True
    num_in_channels: 14
    num_out_channels: 14
    embed_dim: 1024
    depth: 6
    num_heads: 1
    decoder_depth: 1
    decoder_num_heads: 1
    mask_fns:
      - "random_masking_ratio"
      - "random_masking"
    mask_kwargs:
      random_masking_ratio:
        ratio: 0.4
        probability: 1.0
      random_masking:
        num_keep: 256
        probability: 1.0
  datamodule:
    root_dir: "/data/users/mike/data/BigEarthNetFixed"
    bands: "all"
    num_classes: 19
    batch_size: 64
    num_workers: 8
    pin_memory: True
    prefetch_factor: 10
    persistent_workers: True
    load_target: False
logger:
  name: "wandb"
  offline: False
  project_name: "master-thesis"
