trainer:
  accelerator: "gpu"
  devices: [0,1]
  precision: 32
  accumulate_grad_batches: 1
  limit_train_batches: 360
  max_epochs: 100
  limit_val_batches: 0
  benchmark: True
experiment:
  task: "mae_bigearthnet_linearprobing"
  name: "mae_bigearthnet_linearprobing"
  run:
    fit: True
    test: True
  module:
    task_name: "mae"
    model: "mae"
    encoder_name: "vit"
    sensor: "naip"
    bands: "all"
    linear_probing: True
    image_size: 120
    crop_size: 112 #96
    patch_size: 8
    #resume_checkpoint: "epoch=29-step=10800.ckpt"
    batch_size: ${experiment.datamodule.batch_size}
    mean_patches: True
    channel_wise: True
    multi_label: True
    in_channels: 12
    out_channels: 1
    num_classes: 19
    load_checkpoint: "last.ckpt"
    imagenet_pretrained: False
    lr: 1e-1
    optimizer: "SGD"
    optimizer_kwargs:
      weight_decay: 0.0
      momentum: 0.9
    lr_min: 0.0
    warmup_lr_init: 1.5e-7
    num_warmup: 10
    #mask_fns:
    #  - "random_channel_masking"
    #mask_kwargs:
    #  random_channel_masking:
    #    num_keep: 720
    #    probability: 1.0
  datamodule:
    root_dir: "/data/users/mike/data/BigEarthNetStacked"
    # root_dir: "/data/users/mike/data/FFCV"
    bands: "all"
    num_classes: 19
    batch_size: 64
    num_workers: 4
    pin_memory: True
    prefetch_factor: 3
    persistent_workers: True
    load_target: True
    use_ffcv: False
    distributed: True
    batches_ahead: 3
logger:
  name: "wandb"
  offline: False
  project_name: "master-thesis"
