trainer:
  gpus: [0,1,2,3]
  max_epochs: 30
  precision: 32
  benchmark: True
  limit_train_batches: 360
  limit_val_batches: 40 
experiment:
  task: "mae_bigearthnet_finetuning"
  name: "mae_bigearthnet_finetuning"
  run:
    fit: True
    test: True
  module:
    task_name: "mae"
    model: "mae"
    encoder_name: "vit"
    sensor: "naip"
    bands: "all"
    image_size: 120
    crop_size: 112
    patch_size: 8
    batch_size: ${experiment.datamodule.batch_size}
    mean_patches: False
    channel_wise: True
    multi_label: True
    in_channels: 14
    out_channels: 1
    num_classes: 19
    load_checkpoint: "last.ckpt"
    imagenet_pretrained: False
    optimizer: "ADAMW"
    lr: 1e-3
    optimizer_kwargs:
      weight_decay: 0.05
      betas: 
        - 0.9
        - 0.999
    lr_min: 0.0
    warmup_lr_init: 1.5e-7
    num_warmup: 5
  datamodule:
    #root_dir: "/data/users/mike/data/BigEarthNetFixed"
    root_dir: "/scratch/users/mike/data/FFCV"
    bands: "all"
    num_classes: 19
    batch_size: 32
    num_workers: 8
    pin_memory: True
    prefetch_factor: 5
    persistent_workers: True
    load_target: True
    use_ffcv: True
    distributed: True
    batches_ahead: 4
logger:
  name: "wandb"
  offline: False
  project_name: "master-thesis"
