trainer:
  accelerator: "gpu"
  devices: [0,1,2,3]
  precision: "bf16"
  accumulate_grad_batches: 8
  max_epochs: 400
  limit_train_batches: 1.0
  limit_val_batches: 1
  check_val_every_n_epoch: 100
  benchmark: True
  enable_progress_bar: True
  fast_dev_run: False
experiment:
  task: "mae_bigearthnet_train"
  name: "mae_bigearthnet_train"
  run:
    fit: True
    test: False
  module:
    model: "mae"
    encoder_name: "vit"
    sensor: "naip"
    imagenet_pretrained: False
    pretrained: False
    # resume_checkpoint: "last.ckpt"
    image_size: 120
    crop_size: 96
    patch_size: 8
    batch_size: ${experiment.datamodule.batch_size} 
    # create_sharded: True
    channel_wise: True
    channel_shuffle: False
    multi_conv: True
    satmae: True
    mask_tokens_encoder: False
    mask_tokens_decoder: True
    mask_tokens_reduction_encoder: False
    mask_tokens_reduction_decoder: False
    norm_pix_loss: False
    num_in_channels: 12
    num_out_channels: 12
    num_checkpoints_encoder: 0
    num_checkpoints_decoder: 0
    mlp_ratio: 4.0
    embed_dim: 1024
    depth: 24
    num_heads: 16
    decoder_embed_dim: 1024
    decoder_depth: 8
    decoder_num_heads: 16
    mask_fns:
      - "random_masking_ratio"
      - "random_masking"
    mask_kwargs:
      random_masking_ratio:
        ratio: 0.7
        probability: 1.0
      random_masking:
        num_keep: 112
        probability: 1.0
    lr: 1.5e-4
    lr_min: 0.0
    warmup_lr_init: 0.0
    num_warmup: 20
  datamodule:
    #root_dir: "/scratch/users/mike/data/BigEarthNetStacked"
    root_dir: "/scratch/users/mike/data/FFCV"
    bands: "all"
    num_classes: 19
    batch_size: 128
    num_workers: 7
    pin_memory: True
    prefetch_factor: 2
    persistent_workers: False
    load_target: False
    use_ffcv: True
    distributed: True
    batches_ahead: 4
logger:
  name: "wandb"
  offline: False
  project_name: "master-thesis"
