trainer:
  gpus: [1]
  max_epochs: 100
  precision: 32
  benchmark: True
  replace_sampler_ddp: False
  limit_train_batches: 827
experiment:
  task: "mae_naipcdl_train"
  name: "mae_naipcdl_train"
  run:
    fit: True
    test: False
  module:
    model: "mae"
    encoder_name: "vit"
    sensor: "naip"
    imagenet_pretrained: False
    pretrained: False
    image_size: 256
    crop_size: 224
    patch_size: 16
    batch_size: ${experiment.datamodule.batch_size} 
    channel_wise: True
    channel_shuffle: True
    mask_tokens_encoder: False
    mask_tokens_decoder: True
    mask_tokens_reduction_encoder: False
    mask_tokens_reduction_decoder: True
    norm_pix_loss: False
    num_in_channels: 4
    num_out_channels: 4
    mlp_ratio: 1
    embed_dim: 1024
    depth: 16
    num_heads: 6
    decoder_embed_dim: 512
    decoder_depth: 4
    decoder_num_heads: 1
    mask_fns:
      - "random_masking_ratio"
      - "random_masking"
    mask_kwargs:
      random_masking_ratio:
        ratio: 0.6
        probability: 1.0
      random_masking:
        num_keep: 196
        probability: 1.0
  datamodule:
    naip_root_dir: "/data/users/mike/data/NAIP"
    batch_size: 64
    train_length: 50000
    val_length: 3000
    num_workers: 8
    patch_size: 240
    dataset_split: "roi_split_grid"
    number_of_cells: 12
    area_of_interest:
      - -120.25
      - -119.65
      - 36.45
      - 37.05
      - "2016-01-01"
      - "2017-01-01"
      - "EPSG:4326"
      - "EPSG:26911"
    train_sampler_class: "RandomBlockGeoSampler"
    val_sampler_class: "RandomBlockGeoSampler"
    val_pct: 0.14
    test_pct: 0.14
    cache: True
    cache_size: 75
    pin_memory: True
logger:
  name: "wandb"
  offline: False
  project_name: "master-thesis"
