trainer:
  gpus: [0, 1]
  # strategy: "fsdp"
  max_epochs: 800
  precision: 32
  benchmark: True
  replace_sampler_ddp: False
  limit_train_batches: 800
  limit_val_batches: 50 
experiment:
  task: "mae_bigearthnet_train"
  name: "mae_bigearthnet_train"
  run:
    fit: True
    test: False
  module:
    model: "mae"
    encoder_name: "vit"
    sensor: "naip"
    imagenet_pretrained: False
    pretrained: False
    # resume_checkpoint: "last.ckpt"
    image_size: 120
    crop_size: 112
    patch_size: 8
    batch_size: ${experiment.datamodule.batch_size} 
    channel_wise: True
    channel_shuffle: True
    mask_tokens_encoder: False
    mask_tokens_decoder: True
    mask_tokens_reduction_encoder: False
    mask_tokens_reduction_decoder: True
    keep_unreduced_decoder: False
    norm_pix_loss: False
    num_in_channels: 12
    num_out_channels: 12
    use_checkpoint: False
    embed_dim: 1024
    depth: 8
    num_heads: 2
    decoder_embed_dim: 1024
    decoder_depth: 2
    decoder_num_heads: 1
    mask_fns:
      - "random_masking_ratio"
      - "random_masking"
    mask_kwargs:
      random_masking_ratio:
        ratio: 0.7
        probability: 1.0
      random_masking:
        num_keep: 256
        probability: 1.0
  datamodule:
    root_dir: "/data/users/mike/data/BigEarthNetFixed"
    bands: "all"
    num_classes: 19
    batch_size: 64
    num_workers: 8
    pin_memory: True
    prefetch_factor: 5
    persistent_workers: True
    load_target: False
logger:
  name: "wandb"
  offline: False
  project_name: "master-thesis"
