trainer:
  accelerator: "gpu"
  devices: [0,1]
  precision: 32
  max_epochs: 30
  limit_train_batches: 360
  limit_val_batches: 0 
  benchmark: True
experiment:
  task: "mae_bigearthnet_finetuning"
  name: "mae_bigearthnet_finetuning"
  run:
    fit: True
    test: True
  module:
    task_name: "mae"
    model: "mae"
    encoder_name: "vit"
    sensor: "naip"
    bands: "all"
    image_size: 120
    crop_size: 112 # 96
    patch_size: 8
    resume_checkpoint: "last.ckpt"
    batch_size: ${experiment.datamodule.batch_size}
    mean_patches: True
    channel_wise: True
    multi_label: True
    in_channels: 12
    out_channels: 1
    num_classes: 19
    load_checkpoint: "last.ckpt"
    imagenet_pretrained: False
    optimizer: "ADAMW"
    lr: 1e-3
    optimizer_kwargs:
      weight_decay: 0.05
      betas: 
        - 0.9
        - 0.999
    lr_min: 0.0
    warmup_lr_init: 1.5e-7
    num_warmup: 5
    mask_fns:
      - "random_channel_masking"
    mask_kwargs:
      random_channel_masking:
        num_keep: 750
        probability: 1.0
  datamodule:
    root_dir: "/data/users/mike/data/BigEarthNetStacked"
    #root_dir: "/scratch/users/mike/data/FFCV"
    bands: "all"
    num_classes: 19
    batch_size: 32
    num_workers: 4
    pin_memory: True
    prefetch_factor: 5
    persistent_workers: True
    load_target: True
    use_ffcv: False
    distributed: True
    batches_ahead: 4
logger:
  name: "wandb"
  offline: False
  project_name: "master-thesis"
