trainer:
  gpus: [1]
  max_epochs: 100
  precision: 32
  benchmark: True
  replace_sampler_ddp: False
experiment:
  task: "msae_naipcdl_train"
  name: "msae_naipcdl_train"
  run:
    fit: True
    test: False
  module:
    model: "msae"
    encoder_name: "vit"
    sensor: "naip"
    imagenet_pretrained: False
    pretrained: False
    image_size: 256
    crop_size: 224
    patch_size: 16
    batch_size: ${experiment.datamodule.batch_size}
    mean_patches: True
    channel_wise: True
    channel_shuffle: True
    embed_token: True
    embed_token_reduction: True
    num_in_channels: 3
    num_out_channels: 3
    embed_dim: 256
    depth: 6
    num_heads: 1
    mask_fn:
      - "random_masking"
    mask_kwargs:
      random_mask_num_keep: 256
      random_mask_probability: 1.0
  datamodule:
    naip_root_dir: "/data/users/mike/data/NAIP"
    batch_size: 64
    train_length: 50000 #0
    val_length: 3000 #0
    num_workers: 8
    patch_size: 240
    dataset_split: "roi_split_grid"
    number_of_cells: 12
    area_of_interest:
      - -120.25
      - -119.65
      - 36.45
      - 37.05
      - "2016-01-01"
      - "2017-01-01"
      - "EPSG:4326"
      - "EPSG:26911"
    train_sampler_class: "RandomBlockGeoSampler"
    val_sampler_class: "RandomBlockGeoSampler"
    val_pct: 0.14
    test_pct: 0.14
    cache: True
    cache_size: 75
    pin_memory: True
logger:
  name: "wandb"
  offline: False
  project_name: "master-thesis"
