trainer:
  gpus: [1]
  max_epochs: 500
  precision: 32
  benchmark: True
experiment:
  task: "tile2vec_naipcdl_train"
  name: "tile2vec_naipcdl_train"
  run:
    fit: True
    test: False
  module:
    model: "tile2vec"
    encoder_name: "resnet18"
    sensor: "naip"
    imagenet_pretrained: False
    pretrained: False
    image_size: 256
    crop_size: 224
    mean_patches: False
    patch_size: 16
    embed_dim: 1024
    projection_dim: 2048
    depth: 6
    num_heads: 1
    margin: 10
    l2: 0.01
  datamodule:
    naip_root_dir: "/data/users/mike/data/NAIP"
    batch_size: 64
    train_length: 10000
    val_length: 1500
    num_workers: 8
    patch_size: 256
    neighborhood: 512
    dataset_split: "roi_split_grid"
    number_of_cells: 12
    area_of_interest:
      - -120.25
      - -119.65
      - 36.45
      - 37.05
      - "2016-01-01"
      - "2017-01-01"
      - "EPSG:4326"
      - "EPSG:26911"
    train_sampler_class: "TripletBatchGeoSampler"
    val_sampler_class: "TripletBatchGeoSampler"
    train_collate_fn: "stack_triplet_samples"
    val_collate_fn: "stack_triplet_samples"
    val_pct: 0.14
    test_pct: 0.14
    cache: True
    cache_size: 75
    pin_memory: True
logger:
  name: "wandb"
  offline: False
  project_name: "master-thesis"