trainer:
  gpus: 1
  max_epochs: 20
  precision: 16
  benchmark: True
experiment:
  task: "tile2vec_naipcdl_evaluate"
  name: "tile2vec_naipcdl_evaluate"
  run:
    fit: True
    test: True
  module:
    task_name: "tile2vec"
    model: "tile2vec"
    encoder_name: "resnet18"
    sensor: "naip"
    num_classes: 255
    patch_size: 50
    load_checkpoint: ""
    imagenet_pretrained: False
    lr: 0.02
    momentum: 0.9
    weight_decay: 0.000001
    project: False
    projector_embeddings: False
    learning_rate_schedule_patience: 6
  datamodule:
    naip_root_dir: "/scratch/NAIP"
    cdl_root_dir: "/scratch/CDL"
    batch_size: 256
    train_length: 10000
    val_length: 1250
    test_length: 10000
    num_workers: 4
    patch_size: 50
    dataset_split: "roi_split_grid"
    number_of_cells: 12
    area_of_interest:
      - -120.25
      - -119.65
      - 36.45
      - 37.05
      - "2016-01-01"
      - "2017-01-01"
      - "EPSG:4326"
      - "EPSG:26911"
    train_sampler_class: "RandomGeoSampler"
    val_sampler_class: "RandomGeoSampler"
    test_sampler_class: "RandomGeoSampler"
    val_pct: 0.14
    test_pct: 0.14
    cache: True
    cache_size: 75
    pin_memory: True
logger:
  name: "wandb"
  offline: False
  project_name: "master-thesis"
