trainer:
  gpus: 1
  max_epochs: 50
  precision: 32
  benchmark: True
experiment:
  task: "vicreg_naipcdl_train"
  name: "vicreg_naipcdl_train"
  run:
    fit: True
    test: False
  module:
    model: "vicreg"
    encoder_name: "resnet18"
    sensor: "naip"
    imagenet_pretrained: False
    pretrained: False
    projector_num_layers: 3
    projection_dim: 2048
    image_size:
      - 50
      - 50
    lr: 0.0
    min_lr: 0.002
    momentum: 0.9
    eta: 0.001
    weight_decay: 1e-6  # TODO: Add weight decay and adaption filter
    invar_coeff: 25.0
    var_coeff: 25.0
    cov_coeff: 1.0
  datamodule:
    naip_root_dir: "/data/users/mike/data/NAIP"
    batch_size: 64
    train_length: 100000
    val_length: 15000
    num_workers: 4
    patch_size: 50
    dataset_split: "roi_split_grid"
    number_of_cells: 12
    area_of_interest:
      - -120.25
      - -119.65
      - 36.45
      - 37.05
      - "2016-01-01"
      - "2017-01-01"
      - "EPSG:4326"
      - "EPSG:26911"
    train_sampler_class: "RandomGeoSampler"
    val_sampler_class: "RandomGeoSampler"
    val_pct: 0.14
    test_pct: 0.14
    cache: True
    cache_size: 75
    pin_memory: True
logger:
  name: "wandb"
  offline: False
  project_name: "master-thesis"
